// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKxoYpMgdN4oo1SNSpVD9BiDT9bqP_R2M',
    appId: '1:432687305621:web:331dd11c149ca79a625c9c',
    messagingSenderId: '432687305621',
    projectId: 'star-coffee-f161e',
    authDomain: 'star-coffee-f161e.firebaseapp.com',
    storageBucket: 'star-coffee-f161e.appspot.com',
    measurementId: 'G-SK8Q4QFMGM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2I59i3VanTQCFcZwOetAwWpCWJJEpXwY',
    appId: '1:432687305621:android:4fbe256b4f564234625c9c',
    messagingSenderId: '432687305621',
    projectId: 'star-coffee-f161e',
    storageBucket: 'star-coffee-f161e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADt2LO1fOeNk9GjMEvPqocZrSs6ae3Q_c',
    appId: '1:432687305621:ios:7430768561856231625c9c',
    messagingSenderId: '432687305621',
    projectId: 'star-coffee-f161e',
    storageBucket: 'star-coffee-f161e.appspot.com',
    iosClientId: '432687305621-slcduk86lsd8hekk9uhuv9k6n6pvpt7d.apps.googleusercontent.com',
    iosBundleId: 'com.example.starCoffee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADt2LO1fOeNk9GjMEvPqocZrSs6ae3Q_c',
    appId: '1:432687305621:ios:7430768561856231625c9c',
    messagingSenderId: '432687305621',
    projectId: 'star-coffee-f161e',
    storageBucket: 'star-coffee-f161e.appspot.com',
    iosClientId: '432687305621-slcduk86lsd8hekk9uhuv9k6n6pvpt7d.apps.googleusercontent.com',
    iosBundleId: 'com.example.starCoffee',
  );
}
